version: '2'
services:
  prometheus:
    image: ubuntu/prometheus 
    container_name: prometheus
    volumes:
      - ${PWD}:/home
    command:
      - '--config.file=/home/prometheus_config.yml'
    ports: 
      - 9090:9090
    extra_hosts:
      - "metricesHost:172.20.10.2"
  grafana:
    image: docker.io/grafana/grafana
    container_name: grafana
    ports: 
      - 3000:3000
