global:
  scrape_interval: 60s
  scrape_timeout: 10s
  evaluation_interval: 60s
alerting:
  alertmanagers:
  - follow_redirects: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []
scrape_configs:
- job_name: getRealTimeGymAndSwStatus
  honor_timestamps: true
  scrape_interval: 60s
  scrape_timeout: 10s
  metrics_path: "/tpsc-metrics"
  scheme: http
  follow_redirects: true
  static_configs:
  - targets: ["us-central1-tpsc-d27f4.cloudfunctions.net"]