{
 "title": "台北市運動中心狀態圖表",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "健身房目前使用人數百分比",
   "type": "bargauge",
   "description": "該比率是由（目前健身房人數/最大容留人數）x 100%而得出",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "BTSC{label=\"{'label': 'gymCapacityPercentage'}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DASC{label=\"{'label': 'gymCapacityPercentage'}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DTSC{label=\"{'label': 'gymCapacityPercentage'}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "JJSC{label=\"{'label': 'gymCapacityPercentage'}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "NGSC{label=\"{'label': 'gymCapacityPercentage'}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "NHSC{label=\"{'label': 'gymCapacityPercentage'}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "SLSC{label=\"{'label': 'gymCapacityPercentage'}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "SSSC{label=\"{'label': 'gymCapacityPercentage'}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "WHSC{label=\"{'label': 'gymCapacityPercentage'}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "WSSC{label=\"{'label': 'gymCapacityPercentage'}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ZSSC{label=\"{'label': 'gymCapacityPercentage'}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "健身房目前使用人數百分比",
   "type": "timeseries",
   "description": "該比率是由（目前健身房人數/最大容留人數）x 100%而得出",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "BTSC{label=\"{'label': 'gymCapacityPercentage'}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DASC{label=\"{'label': 'gymCapacityPercentage'}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DTSC{label=\"{'label': 'gymCapacityPercentage'}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "JJSC{label=\"{'label': 'gymCapacityPercentage'}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "NGSC{label=\"{'label': 'gymCapacityPercentage'}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "NHSC{label=\"{'label': 'gymCapacityPercentage'}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "SLSC{label=\"{'label': 'gymCapacityPercentage'}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "SSSC{label=\"{'label': 'gymCapacityPercentage'}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "WHSC{label=\"{'label': 'gymCapacityPercentage'}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "WSSC{label=\"{'label': 'gymCapacityPercentage'}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ZSSC{label=\"{'label': 'gymCapacityPercentage'}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "北投運動中心",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "BTSC", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "大安運動中心",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DASC", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "大同運動中心",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DTSC", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "中正運動中心",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "JJSC", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "南港運動中心",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "NGSC", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "內湖運動中心",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "NHSC", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "士林運動中心",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "SLSC", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "松山運動中心",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "SSSC", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "文山運動中心",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "WSSC", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "中山運動中心",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ZSSC", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "萬華運動中心",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "WHSC", "legendFormat": "__auto" }
   ]
  }
 ]
}