{
 "title": "運動中心狀態圖表",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "北投運動中心",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "BTSC", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "大安運動中心",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DASC", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "大同運動中心",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DTSC", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "中正運動中心",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "JJSC", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "南港運動中心",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "NGSC", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "內湖運動中心",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "NHSC", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "士林運動中心",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "SLSC", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "松山運動中心",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "SSSC", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "萬華運動中心",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "WHSC", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "文山運動中心",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "WSSC", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "中山運動中心",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ZSSC", "legendFormat": "__auto" }
   ]
  }
 ]
}